apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    # プロダクションのdomain name!
    - host: af112a50abac2477094d252f1e7406fe-8d024333752eb1a9.elb.ap-northeast-1.amazonaws.com
      http:
        paths:
          # ingress-nginxは、上からマッチするルートが選ばれる
          - path: /api/?(.*)
            backend:
              serviceName: api-srv
              servicePort: 8081
          - path: /?(.*)
            backend:
              serviceName: eks-demo-srv
              servicePort: 8080
