name: deploy-manifests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - run: kubectl apply -f k8s
      - run: kubectl create secret generic eks-demo-local-secrets --from-env-file=.prod.env