name: test-api

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: mansagroup/nrwl-nx-action@v2
      - run: nx test api && nx lint api